#!/usr/bin/env python3
"""
audit_resolved.py — Detect false-positive ATS matches in jobhunter.db
"""

import sqlite3
import json
import re
import time
from urllib.request import urlopen, Request
from urllib.error import HTTPError, URLError

DB_PATH = "jobhunter.db"

STOP = {"the", "of", "and", "inc", "llc", "corp", "co", "ltd", "group",
        "services", "solutions", "international", "global", "na", "us",
        "a", "an", "for"}

def tokenize(name):
    name = re.sub(r"[^a-z0-9\s]", " ", name.lower())
    return {w for w in name.split() if w and w not in STOP}

def name_similarity(target, board_name):
    t1, t2 = tokenize(target), tokenize(board_name)
    if not t1 or not t2:
        return 0.0
    return len(t1 & t2) / len(t1 | t2)

def get_greenhouse_board_name(slug):
    url = f"https://boards-api.greenhouse.io/v1/boards/{slug}"
    try:
        req = Request(url, headers={"User-Agent": "JobHunter-Audit/1.0"})
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return data.get("name")
    except (HTTPError, URLError, json.JSONDecodeError):
        return None

def get_lever_board_name(slug):
    return slug.replace("-", " ")

def get_ashby_board_name(slug):
    url = f"https://api.ashbyhq.com/posting-api/posting-board/{slug}"
    try:
        req = Request(url, headers={"User-Agent": "JobHunter-Audit/1.0"})
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return data.get("organizationName") or data.get("title")
    except (HTTPError, URLError, json.JSONDecodeError):
        return None

def get_smartrecruiters_board_name(slug):
    url = f"https://api.smartrecruiters.com/v1/companies/{slug}"
    try:
        req = Request(url, headers={"User-Agent": "JobHunter-Audit/1.0"})
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return data.get("name")
    except (HTTPError, URLError, json.JSONDecodeError):
        return None

FETCHERS = {
    "greenhouse": get_greenhouse_board_name,
    "lever": get_lever_board_name,
    "ashby": get_ashby_board_name,
    "smartrecruiters": get_smartrecruiters_board_name,
}

def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    rows = conn.execute("""
        SELECT company_name, brand, ats, resolved_token, endpoint
        FROM companies
        WHERE ats IS NOT NULL AND resolved_token IS NOT NULL
    """).fetchall()

    print(f"Auditing {len(rows)} resolved companies...\n")
    print(f"{'Status':<12} {'Sim':>5}  {'Company':<40} {'ATS':>15}  {'Slug':<25}  {'Board Name'}")
    print("-" * 140)

    false_positives = []
    errors = []
    verified = []

    for row in rows:
        cname = row["company_name"]
        brand = row["brand"] or cname
        ats = row["ats"]
        slug = row["resolved_token"]

        fetcher = FETCHERS.get(ats)
        if not fetcher:
            errors.append((cname, ats, "no fetcher"))
            print(f"{'SKIP':<12} {'--':>5}  {brand:<40} {ats:>15}  {slug:<25}  (no name fetcher)")
            continue

        board_name = fetcher(slug)
        time.sleep(0.3)

        if board_name is None:
            errors.append((cname, ats, "fetch failed"))
            print(f"{'ERR':<12} {'--':>5}  {brand:<40} {ats:>15}  {slug:<25}  (fetch failed)")
            continue

        # Compare against both brand and company_name for best match
        sim_brand = name_similarity(brand, board_name)
        sim_legal = name_similarity(cname, board_name)
        sim = max(sim_brand, sim_legal)

        if sim >= 0.25:
            verified.append((cname, brand, ats, slug, board_name, sim))
            print(f"{'OK':<12} {sim:>5.2f}  {brand:<40} {ats:>15}  {slug:<25}  {board_name}")
        else:
            false_positives.append((cname, brand, ats, slug, board_name, sim))
            print(f"{'FALSE':<12} {sim:>5.2f}  {brand:<40} {ats:>15}  {slug:<25}  {board_name}")

    print("\n" + "=" * 140)
    print(f"RESULTS:  {len(verified)} verified  |  {len(false_positives)} FALSE POSITIVES  |  {len(errors)} errors/skipped")

    if false_positives:
        print(f"\nFALSE POSITIVES:")
        print(f"=" * 80)
        for cname, brand, ats, slug, bname, sim in false_positives:
            print(f"  {brand} ({cname})")
            print(f"    Slug '{slug}' on {ats} actually belongs to: {bname}")
            print(f"    Similarity: {sim:.2f}")
            print()

        # Generate fix SQL — quote company_names for SQL safety
        quoted = [cname.replace("'", "''") for cname, *_ in false_positives]
        in_list = ", ".join(f"'{q}'" for q in quoted)

        sql = f"""-- Auto-generated by audit_resolved.py
-- {len(false_positives)} false positives detected

-- Un-resolve false positives
UPDATE companies
SET ats = NULL, resolved_token = NULL, endpoint = NULL,
    job_count = NULL, resolve_status = 'pending'
WHERE company_name IN ({in_list});

-- Delete their ghost jobs
DELETE FROM jobs WHERE company IN ({in_list});
"""
        print(f"\nFIX SQL:")
        print(f"=" * 80)
        print(sql)

        with open("false_positives_fix.sql", "w") as f:
            f.write(sql)
        print("(Saved to false_positives_fix.sql)")
        print(f"\nTo apply:  python3 -c \"import sqlite3; c=sqlite3.connect('jobhunter.db'); c.executescript(open('false_positives_fix.sql').read()); print('Done')\"")

    conn.close()

if __name__ == "__main__":
    main()
